services:
  wordpress:
    restart: always
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - ./src/wordpress:/var/www/html
      - ./:/var/www/html/wp-content/plugins/documentcloud

    depends_on:
      - db
    networks:
      - wp_net

  testing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Testing
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - wp_net
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: wordpress_test
    command: sh -c "composer install && tail -f /dev/null"
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    platform: linux/amd64
    ports:
      - 8180:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wp_net

  db:
    image: mariadb:latest
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    restart: always
    networks:
      - wp_net

volumes:
  db_data:

networks:
  wp_net:
    driver: bridge